<a href="https://colab.research.google.com/github/gwakdh99/gwakdh/blob/master/01_1_%EB%8F%99%EC%8B%9C%EB%B0%9C%EC%83%9D%ED%96%89%EB%A0%AC%2C_PPMI%ED%96%89%EB%A0%AC%2C_%EC%B0%A8%EC%9B%90%EA%B0%90%EC%86%8C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

## Corpus ='you say goodbye and i say hello.' <br>동시발생행렬(Co-occurrence Matrix)</br>

In [0]:
C = np.array([[0, 1, 0, 0, 0, 0, 0], [1, 0, 1, 0, 1, 1, 0], [0, 1, 0, 1, 0, 0, 0], [0, 0, 1, 0, 1, 0, 0], [0, 1, 0, 1, 0, 0, 0], [0, 1, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 1, 0] ])

In [3]:
C

array([[0, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0]])

In [4]:
C.shape[1]

7

In [5]:
np.sum(C)

14

In [6]:
np.zeros_like(C, np.float32)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [9]:
# C 행렬의 열성분의 합을 성분으로 하는 행렬
np.sum(C, axis = 0)

array([1, 4, 2, 2, 2, 2, 1])

In [10]:
# C 행렬의 행성분의 합을 성분으로 하는 행렬
np.sum(C, axis = 1)

array([1, 4, 2, 2, 2, 2, 1])

# PPMI 행렬 만들기

In [0]:
def create_PPMI(mat, eps = 1e-8) : 
    dim = mat.shape[1]
    N = np.sum(mat)
    PPMI_matrix = np.zeros_like(mat, np.float32)
    S = np.sum(mat, axis = 0)
    
    for i in range(dim) :
        for j in range(dim) :
                PPMI_matrix[i][j] = max(0, np.log2(mat[i][j] * N / ( (S[i]*S[j]) + eps ) ))
                
    return PPMI_matrix

In [12]:
W = create_PPMI(C)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in log2
  if __name__ == '__main__':


In [14]:
print(np.round(W, 4)) # round 함수는 소수점 아래에서 반올림할 위치를 지정할 수 있다. 

[[0.     1.8074 0.     0.     0.     0.     0.    ]
 [1.8074 0.     0.8074 0.     0.8074 0.8074 0.    ]
 [0.     0.8074 0.     1.8074 0.     0.     0.    ]
 [0.     0.     1.8074 0.     1.8074 0.     0.    ]
 [0.     0.8074 0.     1.8074 0.     0.     0.    ]
 [0.     0.8074 0.     0.     0.     0.     2.8074]
 [0.     0.     0.     0.     0.     2.8074 0.    ]]


## PPMI행렬에서 SVD (singular value decomposition)를 통해 밀집벡터 표현 얻기

In [0]:
from sklearn.utils.extmath import randomized_svd  # sklearn은 SVD(특잇값분해)를 할 수 있는 모듈로 빠른속도를 가지고 있다. 

In [16]:
dim = 5
U, sigma, VT = randomized_svd(W, dim)
print("%s차 Truncated 특잇값 분해" %(dim))

5차 Truncated 특잇값 분해


In [32]:
print("W행렬은 대부분의 성분이 0인 행렬이었다.")
print("행렬의 모양 : ", np.shape(W))
print(np.round(W, 6))
print()
print("U행렬은 대부분의 성분이 0이 아닌 W에 대응되는 차원감소 행렬이다.")
print("행렬의 모양 : ", np.shape(U))
print(np.round(U, 6)) 

W행렬은 대부분의 성분이 0인 행렬이었다.
행렬의 모양 :  (7, 7)
[[0.       1.807355 0.       0.       0.       0.       0.      ]
 [1.807355 0.       0.807355 0.       0.807355 0.807355 0.      ]
 [0.       0.807355 0.       1.807355 0.       0.       0.      ]
 [0.       0.       1.807355 0.       1.807355 0.       0.      ]
 [0.       0.807355 0.       1.807355 0.       0.       0.      ]
 [0.       0.807355 0.       0.       0.       0.       2.807355]
 [0.       0.       0.       0.       0.       2.807355 0.      ]]

U행렬은 대부분의 성분이 0이 아닌 W에 대응되는 차원감소 행렬이다.
행렬의 모양 :  (7, 5)
[[ 3.40949e-01  1.00000e-06 -1.14686e-01  3.70290e-02 -5.67574e-01]
 [-1.00000e-06  5.97636e-01 -5.53790e-02 -1.71519e-01  6.19797e-01]
 [ 4.36312e-01  1.00000e-06 -4.84172e-01  1.56326e-01  1.37172e-01]
 [-1.00000e-06  4.97828e-01 -2.09055e-01 -6.47484e-01 -4.26660e-01]
 [ 4.36312e-01  1.00000e-06 -4.84172e-01  1.56326e-01  1.37172e-01]
 [ 7.09237e-01  1.00000e-06  6.50844e-01 -2.10139e-01  1.04075e-01]
 [-1.00000e-06  6.28489e-01  2.

## SVD 에 대한 다른 예제 
주어진 행렬 A의 근사행렬 A'를 SVD를 통해서 만들어보자.

In [0]:
def SVD_TEST(A, dim_num = min(A.shape[0], A.shape[1]), rdgit = 7) :
    U, S, VT = randomized_svd(A, dim_num)
    print("다음 행렬의 특잇값 분해를 시작합니다. 차원 = %s" %(dim_num))
    print(np.round(A, rdgit))
    print("-------------------------------------")
    print("왼쪽 직교행렬은 다음과 같습니다. ")
    print(np.round(U, rdgit))
    print()
    print("중앙의 대각행렬은 다음과 같습니다.")
    S = np.diag(S)
    print(np.round(S, rdgit))
    print()
    print("오른쪽의 직교행렬은 다음과 같습니다.")
    print(np.round(VT, rdgit))
    print("-------------------------------------")
    return U, S, VT

In [0]:
A = np.array([[1, 0, 0, 0 ], [3,0, 0, 2], [2,0,3, 0], [1, 0, 0, 0], [0, 1, 0, 0]])

In [138]:
A.shape[0]

5

In [141]:
U1, S1, VT1 = SVD_TEST(A, 3)

다음 행렬의 특잇값 분해를 시작합니다. 차원 = 3
[[1 0 0 0]
 [3 0 0 2]
 [2 0 3 0]
 [1 0 0 0]
 [0 1 0 0]]
-------------------------------------
왼쪽 직교행렬은 다음과 같습니다. 
[[ 0.1864079 -0.0965148  0.       ]
 [ 0.695897  -0.6586243 -0.       ]
 [ 0.6680057  0.7399891  0.       ]
 [ 0.1864079 -0.0965148  0.       ]
 [ 0.        -0.         1.       ]]

중앙의 대각행렬은 다음과 같습니다.
[[4.5129507 0.        0.       ]
 [0.        2.6717064 0.       ]
 [0.        0.        1.       ]]

오른쪽의 직교행렬은 다음과 같습니다.
[[ 0.8412496  0.         0.4440591  0.3084   ]
 [-0.2578593 -0.         0.8309174 -0.4930364]
 [-0.         1.         0.        -0.       ]]
-------------------------------------


SVD를 통해서 A = U S V 로 표현될 때 A가 대부분의 성분이 0인 희소행렬이라면 U는 대부분의 성분이 0이 아닌 밀집벡터행렬로 표현이 됩니다.
통계기반 자연어처리에서는 U의 각 행을 단어의 분산을 표현하는 벡터로 이용합니다.